### ISSUE TITLE
Properly catch HLS crashes

### ISSUE THREAD

**Issue by jahofmann** [esa-tu-darmstadt/tapasco#146]
Pipeline https://git.esa.informatik.tu-darmstadt.de/tapasco/tapasco/-/jobs/29631 crashed with error:
```
[12:28:57 <main: Tapasco$> INFO] Running with configuration: [Configuration @/builds/tapasco/tapasco/default.cfg]
Verbose = Some(verbose)
KernelDir = /builds/tapasco/tapasco/kernel
CoreDir = /builds/tapasco/tapasco/core
ArchDir = /opt/tapasco/vivado/arch
PlatformDir = /opt/tapasco/vivado/platform
Slurm = false
Parallel = false
MaxThreads = unlimited
MaxTasks = unlimited
Jobs = List(HighLevelSynthesisJob(VivadoHLS,None,Some(ArrayBuffer(pynq)),Some(ArrayBuffer(counter)),None))
[12:28:58 <pool-1-thread-1: VivadoHighLevelSynthesis$> INFO] starting run 'counter' for axi4mm@pynq: output in /builds/tapasco/tapasco/core/counter/axi4mm/pynq/hls/axi4mm.log
[12:28:58 <pool-1-thread-1: VivadoHighLevelSynthesis$> INFO] verbose mode verbose is active, starting to watch /builds/tapasco/tapasco/core/counter/axi4mm/pynq/hls/axi4mm.log
[12:29:02 <pool-1-thread-1: VivadoHighLevelSynthesis$> INFO] Vivado HLS finished successfully for 'counter' for axi4mm@pynq
[12:29:02 <pool-1-thread-1: VivadoHighLevelSynthesis$> ERROR] No .zip file with IP core found!
[12:29:02 <pool-1-thread-1: VivadoHighLevelSynthesis$> ERROR] Vivado HLS run for 'counter' @ axi4mm@pynq failed with exception: {}
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:366)
	at scala.None$.get(Option.scala:364)
	at tapasco.activity.hls.VivadoHighLevelSynthesis$.synthesize(VivadoHighLevelSynthesis.scala:84)
	at tapasco.task.HighLevelSynthesisTask.job(HighLevelSynthesisTask.scala:52)
	at tapasco.task.Tasks$ProcessingRunnable.$anonfun$run$1(Tasks.scala:199)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
[12:29:02 <main: HighLevelSynthesis$> INFO] all HLS tasks have finished.
[12:29:02 <main: Tapasco$> ERROR] TaPaSCo finished with errors
```
Which is not really helpful. The error message in the log file is:
```
application-specific initialization failed: couldn't load file "librdi_commontasks.so": libtinfo.so.5: cannot open shared object file: No such file or directory
```

**Comment by sommerlukas** [comment]
Fixed in #191;
