### ISSUE TITLE
relative path names in values for --coreDir and --kernelDir 

### ISSUE THREAD

**Issue by forflo** [esa-tu-darmstadt/tapasco#49]
Something like

`tapasco -v --coreDir ./Cores --kernelDir ./Ips/ hls FooIp -p vcu118`

does not work on my system. In my shell the environment variable `TAPASCO_HOME` is set to `/home/demo/tapasco`.

The error message shows that tapasco appends `Ips` to the `TAPASCO_HOME` environment variable. Is this intended behavior?

```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: kernels directory /home/demo/tapasco/Ips does not exist
	at scala.Predef$.require(Predef.scala:277)
	at de.tu_darmstadt.cs.esa.tapasco.base.ConfigurationImpl.$anonfun$new$2(ConfigurationImpl.scala:77)
	at de.tu_darmstadt.cs.esa.tapasco.base.ConfigurationImpl.$anonfun$new$2$adapted(ConfigurationImpl.scala:74)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:788)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:787)
	at de.tu_darmstadt.cs.esa.tapasco.base.ConfigurationImpl.<init>(ConfigurationImpl.scala:74)
	at de.tu_darmstadt.cs.esa.tapasco.base.ConfigurationImpl.copy(ConfigurationImpl.scala:50)
	at de.tu_darmstadt.cs.esa.tapasco.base.ConfigurationImpl.kernelDir(ConfigurationImpl.scala:60)
	at de.tu_darmstadt.cs.esa.tapasco.parser.GlobalOptions$.mkConfig(GlobalOptions.scala:113)
	at de.tu_darmstadt.cs.esa.tapasco.parser.GlobalOptions$.$anonfun$globalOptions$1(GlobalOptions.scala:104)
	at fastparse.parsers.Transformers$Mapper.parseRec(Transformers.scala:20)
	at fastparse.parsers.Combinators$Sequence$Flat.parseRec(Combinators.scala:316)
	at fastparse.parsers.Transformers$Mapper.parseRec(Transformers.scala:19)
	at fastparse.core.Parser.parseInput(Parsing.scala:376)
	at fastparse.core.Parser.parse(Parsing.scala:358)
	at de.tu_darmstadt.cs.esa.tapasco.parser.CommandLineParser$.apply(CommandLineParser.scala:35)
	at de.tu_darmstadt.cs.esa.tapasco.Tapasco$.main(Tapasco.scala:76)
	at de.tu_darmstadt.cs.esa.tapasco.Tapasco.main(Tapasco.scala)
```

**Comment by cahz** [comment]
Should be fixed in 5543fba
